name: Monkeytype Stats Updater
on:
  schedule:
    - cron: '0 4 * * *' # 12 am
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download SVG
        run: |
          curl -sfo -William-monkeytype-readme-pb.svg \
            "https://monkeytype-readme.zeabur.app/generate-svg/-William/dark_magic_girl?pb=true&rand=$(date +%s)"

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add "./-William-monkeytype-readme-pb.svg" 
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Monkeytype stats"
          git push
